name: dotnet format

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  dotnet-format:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dotnet-version: "8"

    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: dotnet format all
        run: |
          dotnet restore
          dotnet format --verify-no-changes --verbosity diagnostic Senzing.Sdk
          dotnet format --verify-no-changes --verbosity diagnostic Senzing.Sdk.Tests
          dotnet format --verify-no-changes --verbosity diagnostic Senzing.Sdk.Demo
