name: dotnet darwin

on: [pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  dotnet-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - dotnet-version: "8"
            senzingapi-version: "staging-v4"

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: install Senzing runtime
        uses: senzing-factory/github-action-install-senzing-api@v4
        with:
          packages-to-install: "senzingapi-runtime senzingapi-setup"
          senzingapi-version: ${{ matrix.senzingapi-runtime-version }}

      - name: Build with DotNet
        run: |
          dotnet build Senzing.Sdk

      - name: Validate tests compile
        run: |
          dotnet build Senzing.Sdk.Tests

      - name: Run DotNet tests
        run: |
          dotnet test Senzing.Sdk.Tests --logger trx --collect:"XPlat Code Coverage"
