name: dotnet csharpier

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dotnet-csharpier:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dotnet-version: "8"

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - run: |
          dotnet tool restore
          dotnet csharpier --check .
