name: dotnet windows

defaults:
  run:
    shell: pwsh

on:
  pull_request:
    # branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dotnet-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - dotnet-version: "8"
            senzingsdk-version: "staging-v4"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install Senzing SDK
        uses: senzing-factory/github-action-install-senzing-sdk@v3
        with:
          senzingsdk-repository-path: ${{ secrets.SENZING_WIN_BETA_REPOSITORY }}

      - name: Build with DotNet
        run: |
          dotnet test Senzing.Sdk.Demo -p:GeneratePackageOnBuild=false
          dotnet build -c Release Senzing.Sdk -p:GenerateDocumentationFile=true

      - name: Validate tests compile
        run: |
          dotnet build Senzing.Sdk.Tests

      - name: Add to "Path" environment variable
        run: |
          Add-Content $env:GITHUB_PATH "$Env:USERPROFILE\Senzing\er\lib"

      - name: Run DotNet tests
        run: |
          dotnet test Senzing.Sdk.Tests --logger trx --collect:"XPlat Code Coverage"
          cp Senzing.Sdk.Tests/TestResults/*/coverage.cobertura.xml ${{ github.workspace }}

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage.cobertura.xml
          path: ${{ github.workspace }}/coverage.cobertura.xml

  coverage:
    name: Coverage
    needs: dotnet-windows
    permissions:
      pull-requests: write
    uses: senzing-factory/build-resources/.github/workflows/csharp-coverage-comment.yaml@v2
    with:
      thresholds: "85 90"
