name: dotnet code analysis

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  dotnet-code-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dotnet-version: "8"

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Run NuGet restore
        run: |
          dotnet restore sz-sdk-csharp.sln

      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@main
        id: code-analysis
        with:
          build-breaking: true
          all-categories: all
