name: dotnet darwin

on:
  pull_request:
    # branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dotnet-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - dotnet-version: "8"
            senzingapi-version: "staging-v4"

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: install Senzing runtime
        uses: senzing-factory/github-action-install-senzing-api@v4
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}

      - name: Build with DotNet
        run: |
          dotnet build Senzing.Sdk

      - name: Validate tests compile
        run: |
          dotnet build Senzing.Sdk.Tests

      - name: Run DotNet tests
        env:
          DYLD_LIBRARY_PATH: "/opt/senzing/er/lib"
          SENZING_DATA_DIR: "/opt/senzing/er/data"
        run: |
          ln -s /opt/senzing/er/lib/libSz.so /opt/senzing/er/lib/libSz.dylib
          dotnet test Senzing.Sdk.Tests --logger trx --collect:"XPlat Code Coverage"

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage.cobertura.xml
          path: ${{ github.workspace }}/coverage.cobertura.xml

  coverage:
    name: Coverage
    needs: dotnet-darwin
    permissions:
      pull-requests: write
    uses: senzing-factory/build-resources/.github/workflows/csharp-coverage-comment.yaml@v2
    with:
      thresholds: "49 90"
