name: dotnet darwin

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 7 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dotnet-darwin:
    outputs:
      status: ${{ job.status }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        senzingsdk-version: [production-v4, staging-v4]
        include:
          - dotnet-version: "8"

    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: install Senzing SDK
        uses: senzing-factory/github-action-install-senzing-sdk@v3
        with:
          senzingsdk-version: ${{ matrix.senzingsdk-version }}

      - name: configure environment
        run: |
          SENZING_PATH="${HOME}/senzing"
          {
            echo "DYLD_LIBRARY_PATH=${SENZING_PATH}/er/lib"
          } >> "$GITHUB_ENV"

      - name: Build with DotNet
        run: |
          dotnet test Senzing.Sdk.Demo -p:GeneratePackageOnBuild=false
          dotnet build -c Release Senzing.Sdk -p:GenerateDocumentationFile=true

      - name: Validate tests compile
        run: |
          dotnet build Senzing.Sdk.Tests

      - name: Run DotNet tests
        run: |
          dotnet build Senzing.Sdk.TestHelpers
          dotnet test --no-build Senzing.Sdk.Tests --logger trx --collect:"XPlat Code Coverage"
          cp Senzing.Sdk.Tests/TestResults/*/coverage.cobertura.xml Senzing.Sdk.Tests/TestResults/*/coverage.cobertura.${{ matrix.senzingsdk-version }}.xml
          cp Senzing.Sdk.Tests/TestResults/*/coverage.cobertura.${{ matrix.senzingsdk-version }}.xml ${{ github.workspace }}

      - name: Store coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage.cobertura.${{ matrix.senzingsdk-version }}.xml
          path: ${{ github.workspace }}/coverage.cobertura.${{ matrix.senzingsdk-version }}.xml

  coverage:
    name: Coverage
    needs: dotnet-darwin
    permissions:
      pull-requests: write
    uses: senzing-factory/build-resources/.github/workflows/csharp-coverage-comment.yaml@v2
    with:
      thresholds: "85 90"

  slack-notification:
    needs: [dotnet-darwin]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.dotnet-darwin.outputs.status ) && github.event_name == 'schedule' }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.dotnet-darwin.outputs.status }}
