name: windows test

on:
  pull_request:
    # branches: [main]
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  windows-echo:
    runs-on: windows-latest

    steps:
      - name: Add to "Path" environment variable
        run: |
          echo "C:\Program Files\Senzing\er\lib" >> "$GITHUB_PATH"

      - name: Print path
        run: |
          $env:path
          $env:GITHUB_PATH

  windows-append:
    runs-on: windows-latest

    steps:
      - name: Add to "Path" environment variable
        run: |
          printf 'C:\Program Files\Senzing\er\lib' | Out-File -FilePath "$env:GITHUB_PATH" -Encoding utf8 -Append

      - name: Print path
        run: |
          $env:path
          $env:GITHUB_PATH

  windows-add-content:
    runs-on: windows-latest

    steps:
      - name: Add to "Path" environment variable
        run: |
          Add-Content $env:GITHUB_PATH "C:\Program Files\Senzing\er\lib"

      - name: Print path
        run: |
          $env:path
          $env:GITHUB_PATH
