name: windows test

on:
  pull_request:
    # branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows-echo:
    runs-on: windows-latest

    steps:
      - name: Add to "Path" environment variable
        run: |
          echo "C:\Program Files\Senzing\er\lib" >> "$GITHUB_PATH"

      - name: Print path
        run: |
          $env:path

  windows-append:
    runs-on: windows-latest

    steps:
      - name: Add to "Path" environment variable
        run: |
          printf "C:\Program Files\Senzing\er\lib" | Out-File -FilePath "$env:GITHUB_PATH" -Encoding utf8 -Append

      - name: Print path
        run: |
          $env:path
